=== feipengsy/JUNO/XmlObjDesc/xml_files/xld.dtd
<?xml encoding="UTF-8"?>
<!-- ?xml encoding="ISO-8859-1"? -->
<!ELEMENT xdd (attr*, template*)*>
<!ATTLIST xdd
        version          CDATA                             "1.0"
>

<!ELEMENT attr (attr*)>
<!ATTLIST attr
        type               CDATA                             "class"
        name               CDATA                             #REQUIRED
        ns                 CDATA                             #IMPLIED
        base               CDATA                             #IMPLIED
        path               CDATA                             #IMPLIED
        methodlink         (TRUE | FALSE)                    "FALSE"
>
<!ELEMENT template (template*,operators*)*>
<!ATTLIST template
        type               CDATA                             "NONE"
        name               CDATA                             #REQUIRED
        ns                 CDATA                             #IMPLIED
        nestedclass        (TRUE | FALSE)                    "FALSE"
        off                (NO | ALL | FUNCTION )            "NO"    
>
<!ELEMENT operators EMPTY>
<!ATTLIST operators
        name               CDATA                             #REQUIRED   
>

=== feipengsy/JUNO/XmlObjDesc/xml_files/xld.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xdd SYSTEM "xld.dtd">
<xdd>
<!--CLEHP Vector start -->
<attr name="HepAxisAngle" ns="CLHEP">
  <attr name="Hep3Vector" ns="CLHEP"/>
</attr>
<attr name="HepBoost" ns="CLHEP">
  <attr type="struct" name="HepRep4x4Symmetric" ns="CLHEP" />
</attr>
<attr name="HepRotation" ns="CLHEP" />
<attr name="HepLorentzRotation" ns="CLHEP" />
<attr name="HepBoostX" ns="CLHEP" />
<attr name="HepBoostY" ns="CLHEP" />
<attr name="HepBoostZ" ns="CLHEP" />
<attr name="HepEulerAngles" ns="CLHEP" />
<attr name="HepLorentzVector" ns="CLHEP">
  <attr name="Hep3Vector" ns="CLHEP" />
</attr>
<attr name="HepRotationX" ns="CLHEP" />
<attr name="HepRotationY" ns="CLHEP" />
<attr name="HepRotationZ" ns="CLHEP" />
<attr name="Hep2Vector" ns="CLHEP" />
<!--CLEHP Vector end -->
<!--CLHEP Random start -->
<attr name="HepRandomVector" ns="CLHEP">
  <attr name="HepRandomEngine" ns="CLHEP"/>
</attr>
<attr name="RandMultiGauss" base="CLHEP::HepRandomVector" ns="CLHEP">
  <attr name="HepRandomVector" ns="CLHEP">
    <attr name="HepRandomEngine" ns="CLHEP"/>
  </attr>
  <attr name="HepVector" base="CLHEP::HepGenMatrix" ns="CLHEP">
    <attr name="HepGenMatrix" ns="CLHEP" />
  </attr>
  <attr name="HepMatrix" base="CLHEP::HepGenMatrix" ns="CLHEP">
    <attr name="HepGenMatrix" ns="CLHEP" />
  </attr>
</attr>
<!--CLHEP Random end -->
<!--CLHEP Matrix start -->
<attr name="HepDiagMatrix" base="CLHEP::HepGenMatrix" ns="CLHEP">
  <attr name="HepGenMatrix" ns="CLHEP"/>
</attr>
<!--CLHEP Matrix end -->
<attr name="Identifier" />
<!--STL -->
<template name="map" type="T1/T2" ns="std" nestedclass="TRUE">
  <template name="pair&lt;const T1,T2&gt;" ns="std" nestedclass="TRUE" />
  <template name="pair&lt;T1,T2&gt;" ns="std" nestedclass="TRUE" />
  <operators name="iterator" />
  <operators name="const_iterator" />
  <operators name="reverse_iterator" />
</template>
<template name="multimap" type="T1/T2" ns="std" nestedclass="TRUE">
  <template name="pair&lt;const T1,T2&gt;" ns="std" nestedclass="TRUE" />
  <template name="pair&lt;T1,T2&gt;" ns="std" nestedclass="TRUE" />
  <operators name="iterator" />
  <operators name="const_iterator" />
  <operators name="reverse_iterator" />
</template>
<template name="vector" type="T1" ns="std" nestedclass="TRUE">
  <operators name="iterator" />
  <operators name="const_iterator" />
  <operators name="reverse_iterator" />
</template>
<template name="deque" type="T1" ns="std" nestedclass="TRUE">
  <operators name="iterator" />
  <operators name="const_iterator" />
  <operators name="reverse_iterator" />
</template>
<template name="list" type="T1" ns="std" nestedclass="TRUE" >
  <operators name="iterator" />
  <operators name="const_iterator" />
  <operators name="reverse_iterator" />
</template>
<template name="set" type="T1" ns="std" off="ALL" />
<template name="multiset" type="T1" ns="std" off="ALL" />
<!--STL end -->
<!-- HepMC -->
<attr name="GenEvent" ns="HepMC">
  <attr name="GenVertex" ns="HepMC">
    <attr name="FourVector" ns="HepMC"/>
    <attr name="WeightContainer" ns="HepMC"/>
  </attr>
  <attr name="GenParticle" ns="HepMC">
    <attr name="Flow" ns="HepMC"/>
    <attr name="Polarization" ns="HepMC"/>
  </attr>
  <attr name="GenCrossSection" ns="HepMC"/>
  <attr name="HeavyIon" ns="HepMC"/>
  <attr name="PdfInfo" ns="HepMC"/>
</attr>
<!-- HepMC ends -->
</xdd>
